### ISSUE TITLE
Docker and Kubernetes learning

### ISSUE THREAD

**Issue by DevShivmohan** [DevShivmohan/Learning-everything#27]
### Installing docker in Parrot OS
- We need to update our system then type command `sudo apt-get update`.
- Install docker type command `sudo apt-get install docker.io`.
- Now docker installed.
- To test that it installed or not then type command `sudo docker pull hello-world`.
- And run it type command `sudo docker run hello-world`.
- Then its get looks like the below screenshot
![image](https://user-images.githubusercontent.com/72655528/205901769-2864e621-1e92-491f-b0dd-33a6a965d043.png)

**Comment by DevShivmohan** [comment]
**Docker hub link -** [Link](https://hub.docker.com/)
- Pulling images from docker hub - 
  - Syntax `sudo docker pull <image_name>`.
  - i.e. `sudo docker pull openjdk`. 
- Run docker images -
  - Syntax `sudo docker run <image_name>`
  - i.e. `sudo docker run mysql`
  - Interactive mode synatx `sudo docker --name <any_name> -it -d <image_id/name>` [ Its run in non-terminable state ]
  - i.e. run via image id `sudo --name javaContainer -it -d fd6c6c612537`
  - i.e. run via image name `sudo --name javaContainer -it -d openjdk`
- To show all images in our local system - 
  - Type `sudo docker images`.
- Search docker images -
  - Syntax `sudo docker search <image_name>`
  - i.e. `sudo docker search openjdk`

**Comment by DevShivmohan** [comment]
## Login to docker hub
- Docker login with username and token `docker login`
Username :
Password :

## Push docker images local to docker hub and run
 - Build the docker image `docker build -f Dockerfile -t <image_name>:<tag> .`  Where tag is optional, If used anywhere then followed this type of syntax with image name, default tag is **latest**.
    OR
 - Build the docker image `docker build -f Dockerfile -t <image_name> .`
 - Build the docker image `docker build -t <image_name>:<tag> .`
 - Link your local Image with docker hub repository
   - `docker tag <imageName> <username>/<repositoryname>`
   - `docker tag mydockerapp docker5003/javatechonline_repo`

- Push image to dockerhub repository
  - `docker push <username>/<repositoryname>:<tagname>`
  - `docker push docker5003/javatechonline_repo:latest`

- Pull image from dockerhub repository
  - `docker pull <username>/<repositoryname>:<tagname>`
  - `docker pull docker5003/javatechonline_repo:latest`
- Run docker image
  - `docker run -p <docker_container_port>:<project_port> <image_name>`
  - `docker run -p 9900:8080 mydockerapp`
  - `docker run --name <container_name> -it -d <image_name>` run in container detach mode.
  - `docker run --name <container_name> -it -p <container_port>:<project_port> -d <image_name>` run in container detach mode **deployement model**.
  - `docker logs <container_name>` to show the logs of running project.
  - `docker ps` to show the running images.
  - `docker ps -a` to show all the running/stoped images.
  - `docker stop <container_name>` to stop the service which can be started on a port.
  - When we hit API's of the given project port then we need to **docker_container_port** for hiting api's instead of 
**project_port**.
  - Docker container port mapped to the project port.
- Remove docker images
  - Remove image `docker image rm [OPTIONS] IMAGE [IMAGE...]`
  - i.e. `docker image rm shiv` default latest tag
  - i.e. `docker image rm shiv:1.2`
  - i.e. `docker image rm shiv:1.2 --force` delete forcely if any conflicts.

**Comment by DevShivmohan** [comment]
## Spring boot project in docker i.e.
In Dockerfile we keep these code
```

FROM ubuntu:latest
FROM openjdk:17
WORKDIR /usr/src/tx-rx-server
COPY /target/tx-rx-server.jar /usr/src/tx-rx-server/
EXPOSE 8090
ENTRYPOINT ["java","-jar","tx-rx-server.jar"]
```

**Comment by ExceptionGenerator** [comment]
### Build link - https://drive.google.com/drive/folders/1IT7vbBgCHwMds7yUKumVn3vQsWecQXlV?usp=share_link

**Comment by ExceptionGenerator** [comment]
https://drive.google.com/file/d/1pB1Bto-BGzUwmmBMdaIVqM3QR8nZaHC3/view?usp=share_link

**Comment by DevShivmohan** [comment]
Max flow rate delta p -  [Dec192022115706-Trial-Dec192022-115440.xlsx](https://github.com/ExceptionGenerator/Learning-everything/files/10256445/Dec192022115706-Trial-Dec192022-115440.xlsx)


Min flow rate delta P - 
[Dec192022123712-Trial-Dec192022-123057.xlsx](https://github.com/ExceptionGenerator/Learning-everything/files/10256684/Dec192022123712-Trial-Dec192022-123057.xlsx)


Viscus liquid -

Min flow rate - 

[Dec192022131449-Trial-Dec192022-130839.xlsx](https://github.com/ExceptionGenerator/Learning-everything/files/10256935/Dec192022131449-Trial-Dec192022-130839.xlsx)

MAX-



[Dec192022133833-Trial-Dec192022-133319.xlsx](https://github.com/ExceptionGenerator/Learning-everything/files/10257102/Dec192022133833-Trial-Dec192022-133319.xlsx)

**Comment by ExceptionGenerator** [comment]
https://drive.google.com/file/d/1-dlE19ISo_8dF5vPcyJ3RwchI2zq24kb/view?usp=share_link
Commit id-0120ee1@@@

**Comment by DevShivmohan** [comment]
### File upload in Spring boot with Docker container
**Steps for Host configuration** 
 -  Create a directory in your host system i.e. `sudo mkdir /home/storage/`
 - Transfer the ownership to docker of this directory `sudo chown -R root:docker /home/storage/`
 - Give the read/write/execute permission to the directory `sudo chmod -R 777 /home/storage/`.

**Steps for docker container configuration/Spring boot**
 - Define the upload directory path like this `/home/storage/` in Spring boot project.
 - Build docker image.
 - Run docker image syntax `docker run --name <container_name> -v <host_machine_path>:<docker_container_path> -it -p <container_port>:<project_port> -d <image_name>`.
 - Run docker image i.e. `docker run --name file-upload -v /home/storage:/home/storage -it -p 8080:8085 -d file_upload`

**Comment by DevShivmohan** [comment]
### Open MySQL CLI bash of a running container

 - Pull MySQL server image - `docker pull mysql/mysql-server:latest`
 - Run MySQL image in container `docker run --name mysql_server -d mysql/mysql-server:latest`
 - View MySQL root default password `docker logs mysql_server`
 - ![image](https://user-images.githubusercontent.com/72655528/210345527-5e5cd234-f0a6-400e-b54d-5f02560b9a9f.png)
 - Run bash in running container `docker exec -it mysql_server bash`
 - Now you are in bash mode
 - For MySQL type command `mysql -uroot -p` and then paste auto generated password.
 - Now you can not execute any command in mysql.
 - Need to change user password.
 - Type command `ALTER USER 'root'@'localhost' IDENTIFIED BY '[newpassword]';`
 - Now we can execute any mysql command.
 - For more details configuration please [Click here](https://hevodata.com/learn/docker-mysql/).

**Comment by DevShivmohan** [comment]
### Open ubuntu as a CLI in a docker container
 - Pull Ubuntu with specified tag `docker pull ubuntu:20.04`
 - Run it with interactive mode  [ bash ]  - `docker run -ti --rm ubuntu /bin/bash`
 - Now you are in Ubuntu OS.
 - ![image](https://user-images.githubusercontent.com/72655528/210347897-c6b93c61-9612-4771-a570-5571a90f08ff.png)

**Comment by DevShivmohan** [comment]
### Kubernetes run and forword to port
 -  Run cluster type command `kubectl apply -f <kubernetes_yaml_file>`.
 - Spring boot app [project] port **8090**.
 - Get running pods `kubectl get pods` then copy name of the cluster.
 - Forwording application port to the cluster type command `kubectl port-forword <cluster_name> <cluster_port>:<project_port>`
 - Now you can access it via <cluster_port> during API calls;
 - For more info please refer this [Link](https://kubernetes.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/);
 - To stop the all pods and delete it type command `kubectl delete all --all --namespace default`
 - Now all resources will be deleted;

**Comment by DevShivmohan** [comment]
### To start the minikube use mentioned cmd in screenshot

![image](https://github.com/user-attachments/assets/b05c6d78-3c90-4f84-93dc-8a2fe2fcecc4)


### To solve the minikube start problem

![image](https://github.com/user-attachments/assets/1cf0749b-b124-4216-b1a8-31550ab4f43f)


make docker as non-root login, to sort out the problem refer the link - https://docs.docker.com/engine/install/linux-postinstall/.


- To install kubectl in linux follow the steps - https://kubernetes.io/docs/tasks/tools/
- To install the minikube tool for kubernets - https://minikube.sigs.k8s.io/docs/start/?arch=%2Flinux%2Fx86-64%2Fstable%2Fbinary+download#Ingress

**Comment by DevShivmohan** [comment]
### First kubernets deployment yaml file for nginx as of now

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    environment: test
  name: testdeploy
spec:
  replicas: 3
  selector:
    matchLabels:
      environment: test
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        environment: test
    spec:
      containers:
      - image: nginx:1.16
        name: nginx
```

![image](https://github.com/user-attachments/assets/03465eb3-cecd-41a2-87d3-8c02c25e2981)

**IMP Note**
- In future if our service version will change then just need to pass the tag of the docker image in the existing yaml file and just apply with kubectl, after that replicas will update the pods within specified minReadySeconds.

**Comment by DevShivmohan** [comment]
### IMP commands

- To stop the replicas then specify the `replicas:0` in your yaml file.
- And then apply the updated yaml file using `kubectl apply -f normal-deployment.yaml`, after that replica has 0 and then you can delete the replica.
- Delete replica `kubectl delete rs replica_name`.
- To show the running pods use cmd `kubectl get pods`.
- To show the running replicas use cmd `kubectl get rs`.

**Comment by DevShivmohan** [comment]
### Deployment one of the websocket-service

```

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    environment: test
  name: websocketservicedeploy
spec:
  replicas: 3
  selector:
    matchLabels:
      environment: test
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        environment: test
    spec:
      containers:
      - image: devshivmohan/web-socket-service
        name: websocketservice
        ports:
          - containerPort: 8080  # Port inside the container
---
apiVersion: v1
kind: Service
metadata:
  name: websocketservice
  labels:
    environment: test
spec:
  selector:
    environment: test
  ports:
    - protocol: TCP
      port: 8080          # Port exposed by the Service
      targetPort: 8080    # Port on the container
      nodePort: 30000     # Port on the Node (accessible from localhost)
  type: NodePort         # Type to expose the service via NodePort

```


**Get Node IP:**
- If you're running Kubernetes locally with Minikube, use: `minikube ip`.
- For other setups, use the IP address of one of your Kubernetes nodes. You can find it with: `kubectl get nodes -o wide`

**Access the Service:**
- Open your browser or use curl to access: `http://<node-ip>:30000` , IP minikube ip
- ![image](https://github.com/user-attachments/assets/23cd4d65-deae-4433-a0eb-33e2d18e5d19)
- ![image](https://github.com/user-attachments/assets/d57e4a10-3b15-448c-9a07-a6bb6f92b708)

**Comment by DevShivmohan** [comment]
### To scale replicas automatically in kubernets deployment 

To automatically scale the number of replicas based on the load, you can use Kubernetes Horizontal Pod Autoscaler (HPA). The HPA adjusts the number of replicas for a Deployment based on observed CPU utilization or custom metrics.

Here’s how you can set up HPA for your websocketservice:

1. Ensure Metrics Server is Installed
First, ensure that the Metrics Server is installed in your cluster as HPA requires it to collect metrics. You can install it using:

- `kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml`

2. Create the Horizontal Pod Autoscaler
Create an HPA YAML file to automatically scale the replicas. Here's an example configuration:

```
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: websocketservice-hpa
  labels:
    environment: test
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: websocketservicedeploy
  minReplicas: 1          # Minimum number of replicas
  maxReplicas: 10         # Maximum number of replicas
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50  # Target CPU utilization percentage

```

3. Apply the HPA Configuration
Save the HPA configuration to a file (e.g., hpa.yaml) and apply it:

- `kubectl apply -f hpa.yaml`


Key Components of the HPA Configuration:
scaleTargetRef: Specifies the target Deployment for autoscaling.
minReplicas and maxReplicas: Define the minimum and maximum number of replicas.
metrics: Defines the metrics used for scaling. In this example, it scales based on CPU utilization.
Monitoring and Verification
Check HPA Status: Use kubectl get hpa to monitor the HPA status.
Describe HPA: Use kubectl describe hpa websocketservice-hpa to get detailed information about the HPA.
With this setup, Kubernetes will automatically adjust the number of replicas for your websocketservice Deployment based on CPU utilization, helping to handle varying loads effectively.
