### ISSUE TITLE
Linux Learning

### ISSUE THREAD

**Issue by DevShivmohan** [DevShivmohan/Learning-everything#4]
### Reseting Network Manager command
- sudo NetworkManager reset

### Having the wireless card engage into monitor mode--
- Type **iwconfig** command now you have see the managed mode and also default value is managed.
- Type **sudo airmon-ng check kill** then kill  the network interface card
- Type **sudo airmon-ng start wlp1s0** interface in monitor mode.
- Type **sudo iwconfig** to verify.

### To revert interface in managed mode--
- Type **sudo airmon-ng stop wlp1s0mon** and it will be in managed mode.

### Deauth packets in LAN network--
- Type **airodump-ng wlp1s0mon** to scan all networks.
- Type **airodump-ng --bssid [BSSID] --channel [CH] wlp1s0mon** where BSSID is targeted and CH are channel no.
- Type **aireplay-ng -0 0 -a [BSSID] -c [STATION] wlp1s0mon** where STATION are single client Mac address, this attack applicable for single client.
- Type **aireplay-ng -0 0 -a [BSSID] wlp1s0mon** this is applicable for all clients.

**Comment by DevShivmohan** [comment]
### To show recently used commands in LINUX
  - **Type command - `history`** .
  - Its show's all the used commands recently.
![image](https://user-images.githubusercontent.com/72655528/194846991-7dcd951b-a6ae-4f95-96f6-2c11b6a927dc.png)

**Comment by DevShivmohan** [comment]
### To delete specific line from recently used history in Linux
 - Specific line.
   - **Type command** - ` history -d <line number>`;  
 - Entire content.
   - **Type command** - ` history -c`;

**Comment by DevShivmohan** [comment]
### Zip/Unzip files
- Zip files
  - **Syntax**  `zip zip_file_name_without_extension file1 file2 file3......`
  - **Example** `zip SpectrumBackend Spectrum_Backend.jar info.txt *.class`
- Unzip file 
  - **Syntax** `unzip unzip_file_name_with_extension`
  - **Example** `unzip SpectrumBackend.zip`

**Comment by DevShivmohan** [comment]
### OS [Linux] file permissions
- When execute command `ls -l`
- Looks like this.
- ![image](https://user-images.githubusercontent.com/72655528/207308914-007059e0-cc31-40e5-bd9f-9cf8559c6c96.png).
- Descriptions of the permissions.
- ![image](https://user-images.githubusercontent.com/72655528/207363195-45a1869e-7435-4f7a-ad43-178a163dc7e4.png)
- ![image](https://github.com/DevShivmohan/Learning-everything/assets/72655528/01c5deb5-0b0b-4e8a-8174-55432442e252)



### Change permission of a directory/file 
- Syntax `chmod <permission> directory/file`
- i.e. `chmod 777 spectrum-backend`

### Change ownership of a directory/file 
- Syntax `sudo chown <user_name> directory/file`
- i.e. `sudo chown root spectrum-backend`
- If want to see the changed permission then type `ls -l` then shows

**Comment by DevShivmohan** [comment]
For Linux dir/file permissions refer - [Link](https://www.pluralsight.com/blog/it-ops/linux-file-permissions)

**Comment by DevShivmohan** [comment]
### Configure Java in Linux
 - Type command `update-alternatives --config java` and then type selection number and then press enter.
 - Install java 17 LTS `sudo apt install openjdk-17-jdk openjdk-17-jre` for more [Refer](https://www.rosehosting.com/blog/how-to-install-java-17-lts-on-ubuntu-20-04/)

**Comment by DevShivmohan** [comment]
### Format bootable pendrive in linux
- Type `df` command, The terminal prints out a list of all mounted partitions and relevant information: used space, available space, used space percentage, and the path. Locate the USB in the list and find the corresponding device. In this example, the USB drive is **/dev/sdb1**.
![image](https://github.com/DevShivmohan/Learning-everything/assets/72655528/2245120a-6252-4318-9c50-8fc3c5872a8a)
- **Unmount the USB drives before formatting. To do so, run this command:** `sudo umount /dev/sdb1`.
- After unmounting, format the USB drive using the preferred file system (replace **sdb1** with the name of your device). 
  - To format a USB drive with FAT32 file system, use. `sudo mkfs.vfat /dev/sdb1`.
  - To format a USB drive using the NTFS file system run. `sudo mkfs.ntfs /dev/sdb1`.
  - To format a USB drive in accordance with the exFAT file system use. `sudo mkfs.exfat /dev/sdb1`.
- Confirm the formatting process has completed successfully. `sudo fsck /dev/sdb1`.
- ![image](https://github.com/DevShivmohan/Learning-everything/assets/72655528/e77fb4a9-5e06-4ed5-a637-6a5e2de2bc56).
- A USB drive with no files indicates successful formatting.
- Now Pendrive has successfully formatted.
- For more information please refer this [Link](https://phoenixnap.com/kb/linux-format-usb).

**Comment by DevShivmohan** [comment]
### Set installed software path in environment variable Ubuntu


**For example I'm setting Gradle path**
- **Open Terminal:** Open a terminal on your Ubuntu system.
- **Edit .bashrc File:** You can set the Gradle path by adding it to your shell's configuration file, such as .bashrc. Open the .bashrc file using a text editor like nano or vim. 
- Type the command `nano ~/.bashrc`.
- **Add Gradle Path:** Scroll to the end of the .bashrc file and add the following line, replacing /path/to/gradle with the actual path to your Gradle installation directory:
- **Syntax** `export PATH=$PATH:/path/to/gradle/bin`.
- **Example**  `export PATH=$PATH:/opt/gradle/gradle-8.3/bin` This is in our system, in case your may be different.
- Reload the .bashrc file by typing the command `source ~/.bashrc`.
- Now everything is done you can access your software via terminal.

**Comment by DevShivmohan** [comment]
[hdfc_account_open.pdf](https://github.com/DevShivmohan/Learning-everything/files/12438479/723fb80a-2dde-42a3-9793-7ae1be57c87f.pdf)

**Comment by DevShivmohan** [comment]
### Set timezone in UTC on ubuntu

![image](https://github.com/DevShivmohan/Learning-everything/assets/72655528/e890fcaa-eab2-4f4c-af15-68ec8780a842)

**Comment by DevShivmohan** [comment]
### Set a docker-compose up at the OS start-up (Daemon process)

- Create `docker-compose.yml` file like below data.
- <img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/db3e2c57-b674-450c-8b7e-dee49d383487" />

```
services:
  postgres:
    image: timescale/timescaledb:latest-pg16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 6eec064aae574c619f0f13783c0dd310
      POSTGRES_DB: rd_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "shared_preload_libraries=timescaledb"]

  rd-service:
    image: devshivmohan/rd-service
    container_name: rd-service
    restart: always
    pull_policy: always
    volumes:
      - ./logs:/home/rd-service/logs
    ports:
      - "8005:8005"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/rd_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 6eec064aae574c619f0f13783c0dd310

volumes:
  postgres_data:


```
- create a yml file inside `/etc/systemd/system/rd-docker-compose.service`
- And save data into like below
```
[Unit]
Description=RD Service with Docker Compose
Requires=docker.service
After=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=/home/admin1/shiv-deck/rd-service
ExecStart=/usr/bin/docker-compose up -d
ExecStop=/usr/bin/docker-compose down
TimeoutStartSec=0

[Install]
WantedBy=multi-user.target
```
- Configure according to your requirement.
- Change permission of this file as `777`
- Daemon reload it as cmd `sudo systemctl daemon-reload`.
- Link it as cmd `sudo systemctl enable rd-docker-compose.service`.
- Start immediatly if needed as cmd `sudo systemctl start rd-docker-compose.service`
-
